[package]
name = "keylight-ctl"
description = "Control Key Lights over their local HTTP API"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap.workspace = true
dirs.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
ureq = { version = "2", features = ["json"] }
